### ISSUE TITLE
rule readjustment (HPoW)

### ISSUE THREAD

**Issue by jonDoe01** [getlynx/Lynx#2]
taking in consideration the current HPoW rules the max diff will not pass 0.5 because the rule 2 & supply don't allow it  .. but, even with a diff of 0.5 a CPU miner will struggle very hard to mine the coin which could lead to unwanted behavior on the network.. so, I recommend the following changes:

```
      consensus.HardForkRule2params = {{2680000, 2},
                                         {3230000, 1},
                                         {3730000, 0.5};
```

_this will protect the network from asic army to raise the difficulty to unwanted levels (above 0.004)_

```

consensus.HardForkRule2LowerLimitMinBalance =6500000*COIN;

```

_this will prevent a potential attack on the network (bypassing all rules attack)..._ 

conclusion: using my adjustment, an attacker will require a MINIMUM of 390 million coins in order to initiate an attack using the MINIMUM combinations which will give him a 1% chance to succeed (a successful attack (100% chance) will required 100 billion coins which it's impossible to obtain because the supply don't allow it) ..

**Comment by sunk818** [comment]
chainparams.cpp: [line 96-98 and line 105](https://github.com/getlynx/Lynx/blob/58cb29f4495426c64a8bb5d999b3dc40d3ef6612/src/chainparams.cpp)

Can you provide some examples contrasting current rules with your proposed rules? What does Rule 2 look like with your new values using different difficulty and powers? 

Proposed values would not change until block 3.23M as values for block 2.68M are the same.

Can you explain how your proposed values prevent ASIC miners? Unless I did the math wrong, it looks like the required LYNX goes down at 2 difficulty.

The 6.5M minimum sets a higher bar for everyone whether they are CPU or ASIC miners. That creates more centralization (fewer people can buy 6.5M LYNX on exchange due to cost or supply).

**Current values - min 1000 LYNX**

power of 2 (block 2.68M)

~~(0.0002 diff ^ 2) * 1 LYNX  = 4 LYNX~~
~~(0.002 diff ^ 2) * 1 LYNX  = 400 LYNX~~
(0.02 diff ^ 2) * 1 LYNX  = 40 000 LYNX
(0.2 diff ^ 2) * 1 LYNX  = 40 M LYNX
(2 diff ^ 2) * 1 LYNX  = 400 M LYNX

power of 3 (block 3.23M)

~~(0.0002 diff ^ 3) * 1 LYNX  = 0.0008 LYNX~~
~~(0.002 diff ^ 3) * 1 LYNX  = 0.8 LYNX~~
~~(0.02 diff ^ 3) * 1 LYNX  = 800 LYNX~~
(0.2 diff ^ 3) * 1 LYNX  = 800 k LYNX
(2 diff ^ 3) * 1 LYNX  = 800 M LYNX

Current values power of 4 (block 3.73M)

~~(0.0002 diff ^ 4) * 1 LYNX  = 0.000000000000002 LYNX~~
~~(0.002 diff ^ 4) * 1 LYNX  = 0.0016 LYNX~~
~~(0.02 diff ^ 4) * 1 LYNX  = 16 LYNX~~
(0.2 diff ^ 4) * 1 LYNX  = 160K LYNX
(2 diff ^ 4) * 1 LYNX  = 1.6B LYNX

---

**Proposed values - min 6.5M LYNX**

power of 2 (block 2.68M)

~~(0.0002 diff ^ 2) * 1 LYNX  = 4 LYNX~~
~~(0.002 diff ^ 2) * 1 LYNX  = 400 LYNX~~
~~(0.02 diff ^ 2) * 1 LYNX  = 40 000 LYNX~~
(0.2 diff ^ 2) * 1 LYNX  = 40 M LYNX
(2 diff ^ 2) * 1 LYNX  = 400 M LYNX

power of 1 (block 3.23M)

~~(0.0002 diff ^ 1) * 1 LYNX  = 20k LYNX~~
~~(0.002 diff ^ 1) * 1 LYNX  = 200k LYNX~~
~~(0.02 diff ^ 1) * 1 LYNX  = 2M LYNX~~
(0.2 diff ^ 1) * 1 LYNX  = 20M LYNX
(2 diff ^ 1) * 1 LYNX  = 200 M LYNX

power of 0.5 (block 3.73M)

~~(0.0002 diff ^ 0.5) * 1 LYNX  = 1.41M LYNX~~
~~(0.002 diff ^ 0.5) * 1 LYNX  = 4.47M LYNX~~
(0.02 diff ^ 0.5) * 1 LYNX  = 14.14M LYNX
(0.2 diff ^ 0.5) * 1 LYNX  = 44.72M LYNX
(2 diff ^ 0.5) * 1 LYNX  = 141.42 M LYNX
